module.exports = function() {
    $.gulp.task('watch:develop', function() {
        $.gulp.watch(
            [
                `${$.path.pathConfig.folderApp}pug/**/*.pug`,
                `${$.path.pathConfig.folderPublic}${$.path.pathConfig.folderOva}/src/*.pug`,
            ],
            $.gulp.series('pug')
        );
        $.gulp.watch(
            [
                `${$.path.pathConfig.folderPublic}${$.path.pathConfig.folderOva}/src/*.scss`,
            ],
            $.gulp.series('stylesOva:build')
        );
        $.gulp.watch(
            [`${$.path.pathConfig.folderApp}styles/**/*.scss`],
            $.gulp.series('stylesMain:build')
        );
        $.gulp.watch(
            [
                `${$.path.pathConfig.folderApp}assets/**/*.{png,jpg,gif}`,
                `${$.path.pathConfig.folderPublic}${$.path.pathConfig.folderOva}/src/assets/**/*.{png,jpg,gif}`,
            ],
            $.gulp.series('img:dev')
        );
        $.gulp.watch(
            [
                `${$.path.pathConfig.folderPublic}${$.path.pathConfig.folderOva}/src/assets/iframes/**/*.{webm,mp4,mp3,vtt,srt,js,html,css,png,jpg,jpeg,gif,svg}`,
            ],
            $.gulp.series('iframes')
        );
        $.gulp.watch(
            `${$.path.pathConfig.folderApp}core/**/*.{js,css}`,
            $.gulp.series('libsJS')
        );
        $.gulp.watch(
            [`${$.path.pathConfig.folderApp}core/**/*.js`],
            $.gulp.series('jsMain:build')
        );
        $.gulp.watch(
            [
                `${$.path.pathConfig.folderApp}core/**/*.js`,
                `${$.path.pathConfig.folderPublic}${$.path.pathConfig.folderOva}/src/index.js`,
            ],
            $.gulp.series('jsOva:build')
        );
        $.gulp.watch(
            `${$.path.pathConfig.folderPublic}${$.path.pathConfig.folderOva}/src/assets/**/*.{mp4,mp3,vtt,srt}`,
            $.gulp.series('multimedia')
        );
    });

    $.gulp.task('watch', function() {
        $.gulp.watch(
            [
                `${$.path.pathConfig.folderApp}pug/**/*.pug`,
                `${$.path.pathConfig.folderPublic}${$.path.pathConfig.folderOva}/src/*.pug`,
            ],
            $.gulp.series('pug')
        );
        $.gulp.watch(
            [
                `${$.path.pathConfig.folderPublic}${$.path.pathConfig.folderOva}/src/*.scss`,
            ],
            $.gulp.series('stylesOva:dev')
        );
        $.gulp.watch(
            [
                `${$.path.pathConfig.folderApp}assets/**/*.{png,jpg,gif}`,
                `${$.path.pathConfig.folderPublic}${$.path.pathConfig.folderOva}/src/assets/**/*.{png,jpg,gif}`,
            ],
            $.gulp.series('img:dev')
        );
        $.gulp.watch(
            [
                `${$.path.pathConfig.folderPublic}${$.path.pathConfig.folderOva}/src/assets/iframes/**/*.{webm,mp4,mp3,vtt,srt,js,html,css,png,jpg,jpeg,gif,svg}`,
            ],
            $.gulp.series('iframes')
        );
        $.gulp.watch(
            `${$.path.pathConfig.folderApp}core/**/*.{js,css}`,
            $.gulp.series('libsJS')
        );
        $.gulp.watch(
            [
                `${$.path.pathConfig.folderApp}core/**/*.js`,
                `${$.path.pathConfig.folderPublic}${$.path.pathConfig.folderOva}/src/index.js`,
            ],
            $.gulp.series('jsOva:dev')
        );
        $.gulp.watch(
            `${$.path.pathConfig.folderPublic}${$.path.pathConfig.folderOva}/src/assets/**/*.{mp4,mp3,vtt,srt}`,
            $.gulp.series('multimedia')
        );
    });
};
